format = """
[](fg:#1A1A1A)\
[ 󰣇  ](bg:#1A1A1A fg:#66BB6A)\
[](bg:#2B2B2B fg:#1A1A1A)\
$git_branch\
$git_status\
[|](bg:#2B2B2B fg:#1A1A1A)\
$directory\
[|](bg:#2B2B2B fg:#1A1A1A)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](bg:#2B2B2B fg:#1A1A1A)\
$time\
[](fg:#1A1A1A)\
\n$character"""

[directory]
style = "fg:#f7a278 bg:#2B2B2B"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"system_repo" = " "

[git_branch]
symbol = ""
style = "bg:#2B2B2B"
format = '[[ $symbol $branch ](fg:#5C5D8D bg:#2B2B2B)]($style)'

[git_status]
style = "bg:#2B2B2B"
format = '[[($all_status$ahead_behind )](fg:#5C5D8D bg:#2B2B2B)]($style)'

[python]
symbol = ""
style = "bg:#2B2B2B"
format = '[[ $symbol ($version) - $virtualenv ](fg:#5C5D8D bg:#2B2B2B)]($style)'

[nodejs]
symbol = ""
style = "bg:#2B2B2B"
format = '[[ $symbol ($version) ](fg:#5C5D8D bg:#2B2B2B)]($style)'

[rust]
symbol = ""
style = "bg:#2B2B2B"
format = '[[ $symbol ($version) ](fg:#5C5D8D bg:#2B2B2B)]($style)'

[golang]
symbol = ""
style = "bg:#2B2B2B"
format = '[[ $symbol ($version) ](fg:#5C5D8D bg:#2B2B2B)]($style)'

[php]
symbol = ""
style = "bg:#2B2B2B"
format = '[[ $symbol ($version) ](fg:#5C5D8D bg:#2B2B2B)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2B2B2B"
format = '[[  $time ](fg:#66BB6A bg:#1A1A1A)]($style)'
